# Azure Pipeline for Volvo OneView
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

steps:
- checkout: self
  
- script: |
    echo "Checking deployment token..."
    echo "Token starts with: $(echo $AZURE_STATIC_WEB_APPS_API_TOKEN | cut -c1-10)..."
  displayName: 'Verify Token'
  env:
    AZURE_STATIC_WEB_APPS_API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

- task: AzureStaticWebApp@0
  displayName: 'Build And Deploy'
  inputs:
    app_location: '/'
    api_location: ''
    output_location: ''
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
    production_branch: 'main'
    skip_build: true
