# Azure Pipeline for Volvo OneView - Using Azure CLI for deployment
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  
- script: |
    echo "Preparing Volvo OneView deployment..."
    echo "Repository contents:"
    ls -la
  displayName: 'Show Repository Contents'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @azure/static-web-apps-cli
  displayName: 'Install Azure Static Web Apps CLI'

- task: AzureCLI@2
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    azureSubscription: 'YOUR_SERVICE_CONNECTION_NAME' # <-- IMPORTANT: Replace with your Service Connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      swa deploy \
        --app-name "Oneview-v2" \
        --resource-group "RG-INTERNAL-APPS-PRD" \
        --source "/" \
        --verbose
