# Azure Pipeline for Volvo OneView - Using Service Principal for deployment
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  
- script: |
    echo "Preparing Volvo OneView deployment..."
    echo "Repository contents:"
    ls -la
  displayName: 'Show Repository Contents'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @azure/static-web-apps-cli
  displayName: 'Install Azure Static Web Apps CLI'

- task: AzureCLI@2
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    azureSubscription: 'YOUR_SERVICE_CONNECTION_NAME' # This will be ignored, but the task requires it.
    addSpnToEnvironment: true # This makes the Service Principal available
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      swa deploy \
        --app-name "Oneview-v2" \
        --resource-group "RG-INTERNAL-APPS-PRD" \
        --source "/" \
        --tenant-id "$(AZURE_TENANT_ID)" \
        --client-id "$(AZURE_CLIENT_ID)" \
        --client-secret "$(AZURE_CLIENT_SECRET)" \
        --verbose
  env:
    AZURE_CLIENT_ID: $(SWA_CLIENT_ID)
    AZURE_TENANT_ID: $(SWA_TENANT_ID)
    AZURE_CLIENT_SECRET: $(SWA_CLIENT_SECRET)
