# Azure Pipeline for Volvo OneView
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  
- script: |
    echo "Preparing Volvo OneView deployment..."
    echo "Repository contents:"
    ls -la
  displayName: 'Show Repository Contents'

- task: AzureStaticWebApp@0
  displayName: 'Build And Deploy'
  inputs:
    app_location: '/'
    api_location: ''
    output_location: ''
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
    production_branch: 'main'
    skip_build: true
